/* Extracts the glyph bitmaps of a Windows raster .FON (NE executable with FNT resources) into a C
 * array of 256 glyphs, one byte per scanline (the layout of the VGA BIOS ROM font).
 *
 *   fon2h <font.fon>                      list the fonts inside
 *   fon2h <font.fon> <array_name> <height> > out.h
 *
 * Only fixed-width fonts up to 8 pixels wide are supported (that is all the engine needs).
 */
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

static uint16_t u16(const uint8_t *p) { return (uint16_t)(p[0] | (p[1] << 8)); }
static uint32_t u32(const uint8_t *p) { return u16(p) | ((uint32_t)u16(p + 2) << 16); }

int main(int argc, char **argv)
{
    if (argc != 2 && argc != 4) { fprintf(stderr, "usage: fon2h font.fon [name height]\n"); return 2; }
    FILE *f = fopen(argv[1], "rb");
    if (!f) { perror(argv[1]); return 1; }
    fseek(f, 0, SEEK_END); long n = ftell(f); fseek(f, 0, SEEK_SET);
    uint8_t *d = malloc(n);
    if (fread(d, 1, n, f) != (size_t)n) return 1;
    fclose(f);

    if (d[0] != 'M' || d[1] != 'Z') { fprintf(stderr, "not an executable\n"); return 1; }
    uint32_t ne = u32(d + 0x3C);
    if (d[ne] != 'N' || d[ne + 1] != 'E') { fprintf(stderr, "not an NE file\n"); return 1; }
    uint32_t rt = ne + u16(d + ne + 0x24);                 /* resource table */
    unsigned shift = u16(d + rt);
    const uint8_t *p = d + rt + 2;
    unsigned want = argc == 4 ? (unsigned)atoi(argv[3]) : 0;
    int found = 0;

    while (u16(p)) {                                       /* resource type blocks */
        unsigned type = u16(p), count = u16(p + 2);
        p += 8;
        for (unsigned i = 0; i < count; i++, p += 12) {
            if (type != 0x8008) continue;                  /* RT_FONT */
            const uint8_t *fnt = d + ((uint32_t)u16(p) << shift);
            unsigned version = u16(fnt);
            unsigned pixw = u16(fnt + 0x56), pixh = u16(fnt + 0x58);
            unsigned first = fnt[0x5F], last = fnt[0x60];
            unsigned hdr = version >= 0x300 ? 148 : 118;
            unsigned entry = version >= 0x300 ? 6 : 4;
            if (argc == 2) { printf("FNT v%x %ux%u chars %u..%u\n", version, pixw, pixh, first, last); continue; }
            if (pixh != want || pixw > 8 || found) continue;
            found = 1;
            printf("/* generated by tools/fon2h.c from %s: %ux%u, chars %u..%u */\n", argv[1], pixw, pixh, first, last);
            printf("static const unsigned char %s[256 * %u] = {\n", argv[2], pixh);
            for (unsigned c = 0; c < 256; c++) {
                printf("  ");
                for (unsigned y = 0; y < pixh; y++) {
                    uint8_t b = 0;
                    if (c >= first && c <= last) {
                        const uint8_t *e = fnt + hdr + (c - first) * entry;
                        uint32_t off = entry == 6 ? u32(e + 2) : u16(e + 2);
                        b = fnt[off + y];                  /* first byte-column: one byte per scanline */
                    }
                    printf("0x%02X,", b);
                }
                printf("\n");
            }
            printf("};\n");
        }
    }
    if (argc == 4 && !found) { fprintf(stderr, "no %ux? font with that height\n", 8); return 1; }
    return 0;
}
