# Generates port/src/font8x8.h: the 8x8 font behind the BIOS "ROM font" (graphics-mode text) and the text-mode screen.
#
# Glyphs come from Unscii 8 (https://github.com/viznut/unscii, public domain / CC0), mapped from code page 437 to
# Unicode. Four characters Unscii lacks are drawn by hand below.
#
#   usage: mkfont.ps1 -Hex <path to unscii-8.hex> [-Commit <unscii git commit>] [-Out <header>]
param(
    [Parameter(Mandatory)][string]$Hex,
    [string]$Commit = 'unknown',
    [string]$Out = (Join-Path $PSScriptRoot '..\src\font8x8.h')
)
[Text.Encoding]::RegisterProvider([Text.CodePagesEncodingProvider]::Instance)
$cp437 = [Text.Encoding]::GetEncoding(437)

$glyphs = @{}
foreach ($line in Get-Content $Hex) {
    if ($line -match '^([0-9A-F]+):([0-9A-F]{16})$') { $glyphs[[Convert]::ToInt32($Matches[1], 16)] = $Matches[2] }
}

# On screen, code page 437 shows symbols for codes 1-31 and 127 (the code page itself maps them to control codes)
$symbols = 0x263A, 0x263B, 0x2665, 0x2666, 0x2663, 0x2660, 0x2022, 0x25D8, 0x25CB, 0x25D9, 0x2642, 0x2640, 0x266A, 0x266B,
           0x263C, 0x25BA, 0x25C4, 0x2195, 0x203C, 0x00B6, 0x00A7, 0x25AC, 0x21A8, 0x2191, 0x2193, 0x2192, 0x2190, 0x221F,
           0x2194, 0x25B2, 0x25BC
$unicode = @{}
for ($c = 1; $c -le 31; $c++) { $unicode[$c] = $symbols[$c - 1] }
$unicode[127] = 0x2302
for ($c = 32; $c -lt 256; $c++) { if ($c -ne 127) { $unicode[$c] = [int][char]$cp437.GetString([byte[]]@($c))[0] } }

# glyphs Unscii does not have, drawn here (one byte per row, top to bottom, most significant bit leftmost)
$handDrawn = @{
    0x0F = '18DB3CE7E73CDB18'      # sun
    0x7F = '00103C6CC6C6FE00'      # house
    0xA9 = '0000007E60600000'      # reversed not sign
    0xF9 = '0000001818000000'      # small centred dot
}

$sb = New-Object Text.StringBuilder
[void]$sb.AppendLine('/* 8x8 font for the BIOS ROM font and the text-mode screen, indexed by IBM code page 437 character.')
[void]$sb.AppendLine(' *')
[void]$sb.AppendLine(" * Generated by tools/mkfont.ps1. Glyphs: Unscii 8 by Viznut (https://github.com/viznut/unscii, commit $Commit),")
[void]$sb.AppendLine(' * released into the public domain / CC0. Characters 0x0F, 0x7F, 0xA9 and 0xF9 are not in Unscii and were drawn')
[void]$sb.AppendLine(' * for this project. One byte per scanline, most significant bit on the left. */')
[void]$sb.AppendLine('static const unsigned char font8x8[256 * 8] = {')
$missing = @()
for ($c = 0; $c -lt 256; $c++) {
    $h = if ($c -eq 0) { '0000000000000000' } elseif ($handDrawn.ContainsKey($c)) { $handDrawn[$c] } elseif ($glyphs.ContainsKey($unicode[$c])) { $glyphs[$unicode[$c]] } else { $missing += $c; '0000000000000000' }
    $bytes = for ($i = 0; $i -lt 16; $i += 2) { '0x' + $h.Substring($i, 2) }
    [void]$sb.AppendLine('  ' + ($bytes -join ',') + ',')
}
[void]$sb.AppendLine('};')
Set-Content -Path $Out -Value $sb.ToString() -Encoding ascii -NoNewline
"wrote $Out ($($glyphs.Count) Unscii glyphs read; hand drawn: $($handDrawn.Count); still missing: $($missing.Count))"
